// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core_dart/firebase_core_dart.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgiVLD2hFB6ARnmJOzDK1O3aiALEaFevQ',
    appId: '1:105921421001:web:5baafa87e74657837d3718',
    messagingSenderId: '105921421001',
    projectId: 'easyshopping-2306e',
    authDomain: 'easyshopping-2306e.firebaseapp.com',
    storageBucket: 'easyshopping-2306e.appspot.com',
    measurementId: 'G-6J42RKCPTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4i7Fjv8fDQm3Kl600XCdtdor46jup5A',
    appId: '1:105921421001:android:c979052acb3cd8387d3718',
    messagingSenderId: '105921421001',
    projectId: 'easyshopping-2306e',
    storageBucket: 'easyshopping-2306e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZDD0FK3SEo6rLNxjZoDBotz6UXVXjss',
    appId: '1:105921421001:ios:212582e5594699a27d3718',
    messagingSenderId: '105921421001',
    projectId: 'easyshopping-2306e',
    storageBucket: 'easyshopping-2306e.appspot.com',
    iosBundleId: 'com.example.clothShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZDD0FK3SEo6rLNxjZoDBotz6UXVXjss',
    appId: '1:105921421001:ios:212582e5594699a27d3718',
    messagingSenderId: '105921421001',
    projectId: 'easyshopping-2306e',
    storageBucket: 'easyshopping-2306e.appspot.com',
    iosBundleId: 'com.example.clothShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgiVLD2hFB6ARnmJOzDK1O3aiALEaFevQ',
    appId: '1:105921421001:web:64c7955cb27eff337d3718',
    messagingSenderId: '105921421001',
    projectId: 'easyshopping-2306e',
    authDomain: 'easyshopping-2306e.firebaseapp.com',
    storageBucket: 'easyshopping-2306e.appspot.com',
    measurementId: 'G-ZLR9QTJG04',
  );
}
